#ifndef EDOCCLIENTCOMPONENTS_GLOBAL_H
#define EDOCCLIENTCOMPONENTS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EDOCCLIENTCOMPONENTS_LIBRARY)
#  define EDOCCLIENTCOMPONENTSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define EDOCCLIENTCOMPONENTSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EDOCCLIENTCOMPONENTS_GLOBAL_H
