#ifndef EDOCSIMPLEFILEINDEXERENGINE_GLOBAL_H
#define EDOCSIMPLEFILEINDEXERENGINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EDOCSIMPLEFILEINDEXERENGINE_LIBRARY)
#  define EDOCSIMPLEFILEINDEXERENGINESHARED_EXPORT Q_DECL_EXPORT
#else
#  define EDOCSIMPLEFILEINDEXERENGINESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EDOCSIMPLEFILEINDEXERENGINE_GLOBAL_H
