#ifndef EDOCMETADATAFRAMEWORK_GLOBAL_H
#define EDOCMETADATAFRAMEWORK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EDOCMETADATAFRAMEWORK_LIBRARY)
#  define EDOCMETADATAFRAMEWORKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define EDOCMETADATAFRAMEWORKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EDOCMETADATAFRAMEWORK_GLOBAL_H
