#ifndef EDOCFACTORY_GLOBAL_H
#define EDOCFACTORY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EDOCFACTORY_LIBRARY)
#  define EDOCFACTORYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define EDOCFACTORYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EDOCFACTORY_GLOBAL_H
