#ifndef EDOCJSONSERVERPLUGIN_GLOBAL_H
#define EDOCJSONSERVERPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EDOCJSONSERVERPLUGIN_LIBRARY)
#  define EDOCJSONSERVERPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define EDOCJSONSERVERPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EDOCJSONSERVERPLUGIN_GLOBAL_H
