#ifndef EDOCTCPHISTORICCLIENT_GLOBAL_H
#define EDOCTCPHISTORICCLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EDOCTCPHISTORICCLIENT_LIBRARY)
#  define EDOCTCPHISTORICCLIENTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define EDOCTCPHISTORICCLIENTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EDOCTCPHISTORICCLIENT_GLOBAL_H
