#ifndef EDOCINMEMORYTAGGING_GLOBAL_H
#define EDOCINMEMORYTAGGING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EDOCINMEMORYTAGGING_LIBRARY)
#  define EDOCINMEMORYTAGGINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define EDOCINMEMORYTAGGINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EDOCINMEMORYTAGGING_GLOBAL_H
