#ifndef EDOCCONFIGURATION_GLOBAL_H
#define EDOCCONFIGURATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EDOCCONFIGURATION_LIBRARY)
#  define EDOCCONFIGURATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define EDOCCONFIGURATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // EDOCCONFIGURATION_GLOBAL_H
